添加 __iadd__
cqmoe/python-aiocqhttp pull request #50
Opened 2021-04-29 02:11 UTC by cleoold

2021-04-29 06:00 UTC, richardchien requested changes

2021-04-29 06:00 UTC, stdrc commented on aiocqhttp/message.py
> +        def __or__(self, other):
这边是啥意思

2021-04-29 06:00 UTC, stdrc commented on aiocqhttp/message.py
> +                super().append(obj)
关联 #51，这里感觉可以一并改了，obj 应该 deep copy

2021-04-29 06:38 UTC, cleoold commented on aiocqhttp/message.py
> +        def __or__(self, other):
字典的 `|` 也不能在這使用

2021-05-01 03:05 UTC, richardchien approved these changes

2021-05-01 04:37 UTC, cleoold commented on aiocqhttp/message.py
> +                super().append(obj)
TBA

2021-05-01 04:37 UTC, merged