修复从str构造Message时CQ码转义不正确
cqmoe/python-aiocqhttp pull request #58
Opened 2021-07-30 11:18 UTC by mnixry

Fixes #57

2021-07-30 14:15 UTC, richardchien requested changes

2021-07-30 14:15 UTC, richardchien commented on aiocqhttp/message.py
> +                r"\[CQ:(?P<type>[a-zA-Z0-9-_.]+)"
这个地方似乎不需要变更，变更之后没过 lint

如果一定要优雅的话，应该只需要把这里的 `unescape` 移到下面，和 params 统一 `unescape`

2021-07-30 14:15 UTC, richardchien commented on aiocqhttp/message.py
> +                extra_data = {
`data` 的命名不需要变，这里 `v` 改成 `unescape(v)` 就行了

2021-07-30 16:56 UTC, richardchien requested changes

2021-07-30 16:56 UTC, richardchien commented on aiocqhttp/message.py
> -                yield cqcode.group('type'), cqcode.group('params').lstrip(',')
引号先别改吧，保持单引号

2021-07-30 16:57 UTC, richardchien commented
另外就是需要修改一下 changelog，版本标题先叫 `## master`

2021-07-31 03:03 UTC, richardchien approved these changes

2021-07-31 03:06 UTC, richardchien requested changes

2021-07-31 03:06 UTC, richardchien commented on aiocqhttp/message.py
> +                    r'(?:,[a-zA-Z0-9-_.]+=[^,\]]+)*'
这里为什么要把问好去掉？这个等号是可选的，允许 `[CQ:xxx,param]` 这样的形式，意思是 `param` 参数值是空

2021-07-31 10:46 UTC, mnixry commented on aiocqhttp/message.py
> +                    r'(?:,[a-zA-Z0-9-_.]+=[^,\]]+)*'
如果去掉这里问号感觉下面的代码会挂
~~这个地方写的太魔法了, 完全看不懂~~

2021-07-31 10:55 UTC, mnixry commented on aiocqhttp/message.py
> +                    k: unescape(v) for k, v in map(
```suggestion
                    k: unescape(''.join(v)) for k, *v in map(
```
是不是可以这样改来支持没有等号的情况...但是看着可读性也太差了

2021-08-12 05:32 UTC, merged

2021-08-12 05:39 UTC, cleoold commented
没 squash

2021-08-12 05:45 UTC, richardchien commented
> 没 squash

是的……我点完发现忘了换模式

2021-08-12 05:48 UTC, cleoold commented
可以把主分支重設到 f727aeda1c2cc44f4f0364ddb31fdd97cf22864e，再合併一遍.

On Thu., Aug. 12, 2021, 01:45 Richard Chien, ***@***.***>
wrote:

> 没 squash
>
> 是的……我点完发现忘了换模式
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/nonebot/aiocqhttp/pull/58#issuecomment-897365386>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADKGVB53Z5VXJTZVPPRMGJDT4NNXFANCNFSM5BIKN4AA>
> .
>

2021-08-12 05:49 UTC, kj415j45 commented
@cleoold bad practice tho :(

2021-08-12 05:50 UTC, richardchien commented
> 可以把主分支重設到 [f727aed](https://github.com/nonebot/aiocqhttp/commit/f727aeda1c2cc44f4f0364ddb31fdd97cf22864e)，再合併一遍.

不折腾了吧，感觉无伤大雅